services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - V:\shell_scripting\scripts:/scripts:rw
    restart: always
    image: ubuntu-vim
    container_name: ubuntu-vim-v
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:
      - COMPOSE_LOGGING_DRIVER=debug
